### ISSUE TITLE
Run ExaAM workflow with core/integrated core components

### ISSUE THREAD

**Issue by mturilli** [ExaWorks/SDK#100]
- Modify/Adopt ExaAM CI implementation of workflow
- Implement with SDK technologies (currently RCT and Swift/T)

**Comment by mturilli** [comment]
@rafaelfsilva needs pointers to ExaAM workflow. @mturilli to investigate and report.

**Comment by mturilli** [comment]
Ticket was refocused. @mtitov to code ExaAM workflow as an EnTK application as per ExaAM's developers requirements.

**Comment by mturilli** [comment]
@mtitov any update on this?

**Comment by mtitov** [comment]
Slides from ExaAM All Hands meeting - https://docs.google.com/presentation/d/1-A4TwA_k2q4S_P-V1sul1LId2h5PdvRJNXSBNC2I3eQ/edit?usp=sharing

**Comment by mtitov** [comment]
https://github.com/ExascaleAM/Workflows
