### ISSUE TITLE
CI: Get results from llnl ci into MR screen

### ISSUE THREAD

**Issue by zekemorton** [ExaWorks/SDK#105]
There should be a way for gitlab to transmit if the pipeline passes or fails to GitHub in the case of a MR

**Comment by zekemorton** [comment]
This will only work for PR's from one branch in the repo to another. The current workflow for SDK is to submit PR's from forked repos so this may not be feasible unless we make changes in that area.

**Comment by mturilli** [comment]
Agreed not to do this.
