### ISSUE TITLE
RADICAL tutorial within a docker container

### ISSUE THREAD

**Issue by mturilli** [ExaWorks/SDK#125]

**Comment by mturilli** [comment]
After the tutorial, publish the container as a general purpose example container.

**Comment by andre-merzky** [comment]
@zekemorton mentioned we could use the SDK CI containers and mount the tutorial into it.  We'll investigate this option next week.

**Comment by mturilli** [comment]
Container + existing Jupyter should suffice for RADICAL-Cybertools.
