### ISSUE TITLE
Test Parsl+Flux 

### ISSUE THREAD

**Issue by mturilli** [ExaWorks/SDK#144]
- Fix existing sh script
- Report back to the dashboard

**Comment by mtitov** [comment]
Current error message reported by LLNL CI
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'parsl.tests.test_flux'
2022-11-15T20:32:12.703872Z sched-fluxion-qmanager.err[0]: update_on_resource_response: exiting due to sched-fluxion-resource.notify failure: Operation canceled
ERROR: usage: __main__.py [options] [file_or_dir] [file_or_dir] [...]
__main__.py: error: unrecognized arguments: --config=local --tap-stream
  inifile: None
  rootdir: /usr/WS1/titov1/gitlab-runner/builds/mJR6TrtB/000/gitlab/Exaworks/SDK

2022-11-15T20:32:16.292510Z broker.err[0]: rc2.0: python3 -m pytest --config=local --tap-stream Exited (rc=4) 2.0s
```

**Comment by hategan** [comment]
I can't really reproduce this.

I extracted the build and test commands from the github ci .yml and ran them locally. I didn't do the full matrix; only ubuntu2004_pip_openmpi_3.7. The test above succeeded.

However, it looks like the llnl ci is doing it via spack, so I will try that next, but converting that .yml into something useful is considerably harder.

The error I see above indicates that parsl wasn't actually installed, which shouldn't technically be possible if the build/install succeeded. But even if it didn't, the test is not the step at which we should find out that it didn't.

**Comment by mtitov** [comment]
@hategan Mihael, looks like it is related to the version of Parsl in spack, which is [1.1.0](https://github.com/spack/spack/blob/f52f6e99dbf1131886a80112b8c79dfc414afb7c/var/spack/repos/builtin/packages/py-parsl/package.py#L15), but `test_flux` became available since 1.2.0

**Comment by hategan** [comment]
Ah, that makes sense. Thanks @mtitov!

**Comment by mturilli** [comment]
@mtitov @hategan was this addressed?

**Comment by mtitov** [comment]
Resolved ([parsl in spack](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/py-parsl/package.py))
