### ISSUE TITLE
Upstream Parsl Flux patch

### ISSUE THREAD

**Issue by dongahn** [ExaWorks/SDK#15]
This should be done to make Issue Parsl+Flux pair-wise testing easy (Issue #11)
(James Corbett). 

The parsl team try James' patch on LLNL system to have the final validation for James's PR review.
@yadudoc and @hategan.

**Comment by dongahn** [comment]
@hategan will talk to @yadudoc about this.

**Comment by yadudoc** [comment]
Hi @dongahn, could we get started with a draft PR over on Parsl so that we can review the executor and figure how best to get James' work integrated? I'll message James about this.

**Comment by jameshcorbett** [comment]
https://github.com/Parsl/parsl/pull/2051

**Comment by jameshcorbett** [comment]
PR has been merged.
