### ISSUE TITLE
"Docker is sunsetting Free Team organizations"

### ISSUE THREAD

**Issue by mtitov** [ExaWorks/SDK#176]
We do have a free team organization at the DockerHub - https://hub.docker.com/u/exaworks, and it is used as docker registry for all our containers.

Yesterday there was the following email
```
Free Team organizations are a legacy subscription tier that no longer exists. 
This tier included many of the same features, rates, and functionality as a 
paid Docker Team subscription.

After reviewing the list of accounts that are members of legacy Free Team 
organizations, we’ve identified yours as potentially being one of them.

If you own a legacy Free Team organization, access to paid features — 
including private repositories — will be suspended on April 14, 2023 (11:59 pm UTC). 
Upgrade your subscription before April 14, 2023 to continue accessing your organization.

If you don’t upgrade to a paid subscription, Docker will retain your organization data 
for 30 days, after which it will be subject to deletion. During that time, you will maintain 
access to any images in your public repositories, though rate limitations will apply. 
At any point during the 30-day period, you can restore access to your organization 
account if you upgrade to a paid subscription.
```

[FAQ](https://em.docker.com/NzkwLVNTQi0zNzUAAAGKf9vaXkG7ZuVeZQWR6KBaUUVB922C2Zw5XKmVFQjKLs0aK1hPfHHyo1qLYjf-So0wKS7VPmkWIDTW5dg=)

Thus the question: either we want to switch to a paid team account (in case we need team features) or it is possible to have a "personal" [free] account which will be used for exaworks (it is not possible to convert organization account into personal to preserve the name; my guess is that need to delete org and re-create as a personal account, but it wasn't tested)

**Comment by hategan** [comment]
I guess if the docker bros say we should pay or else, we should probably pay.

But since we're paying anyway, we could also consider an alternative registry, such as https://aws.amazon.com/ecr/

**Comment by hategan** [comment]
PS: I gear GitLab has a docker repo.

**Comment by mtitov** [comment]
I've missed this part from FAQ, and that what we should follow
```
Docker continues to offer a specific Docker-Sponsored Open Source (DSOS) program for open-source 
projects, and it is not affected by the sunsetting of Free Team organizations. For new users interested 
in joining DSOS from a previous Free Team organization, we will defer any organization suspension or 
deletion while DSOS application is under review, and give organizations at least 30 days before we 
suspend the organization if the application is ultimately rejected. We are listening to feedback and may 
offer additional programs or plans based on your input.
```
Docker-Sponsored Open Source (DSOS) program for open-source projects - https://www.docker.com/community/open-source/application/

**Comment by Vad1mo** [comment]
There is a [Docker-Sponsored Open Source Program](https://www.docker.com/community/open-source/application/) which might be applicable to you.

If, for some reason, this isn't working out, we are happy to help you out. We operate a Harbor-based [container registry as a service ](https://container-registry.com/)that has many benefits to other registries.

**Comment by wilke** [comment]
Thanks everyone. 
we have to:

If you haven’t already, please take the time to update your project’s Hub pages to include a detailed project description, links to your project source code, as well as contributing guidelines, and a link to your organization’s website. Projects lacking this information may not receive the Docker Sponsored Open Source badging for their images on Docker Hub
