### ISSUE TITLE
[CI Request]: SmartSim

### ISSUE THREAD

**Issue by MattToast** [ExaWorks/SDK#200]
Please fulfill the initial requirements described in [Contributing to SDK](https://exaworkssdk.readthedocs.io/en/latest/contribute.html).

1. **CI Request** includes the following information about the software tool:

- [x] Description of the tool: A workflow library that makes it easier to use common Machine Learning (ML) libraries, like PyTorch and TensorFlow, in High Performance Computing (HPC) simulations and applications. SmartSim launches ML infrastructure on HPC systems alongside user workloads.
- [x] GitHub repository (URL): https://github.com/CrayLabs/SmartSim
- [x] Supported package managers: **pip**, ~conda~, **spack**
- [x] Specific version to be used (i.e., "stable"): `v0.5.0` (latest release on github)
- [x] Possibility to run **the latest** version is optional: `develop` branch on github
- [x] List of all dependencies 
  - Direct dependencies:
    - Build Dependencies:
      - setuptools
      - wheel
    - Binary Dependencies:
      - Python
      - Redis
      - RedisAI
      - Libtensorflow (optional)
      - Libtorch (optional)
      - Onnxruntime (optional)
    - Python Packages:
      - coloredlogs
      - filelock
      - protobuf
      - psutil
      - redis
      - smartredis
      - tabulate
      - tqdm
      - onnx (optional)
      - onnxmltools (optional)
      - scikit-learn (optional)
      - skl2onnx (optional)
      - tensorflow (optional)
      - torch (optional)
      - torchvision (optional)
  - Transitive dependencies (dependencies of dependencies)
    - Build Dependencies:
      - bazel
      - cmake
      - cython
      - ninja
      - swig
    - Binary Dependencies:
      - blas
      - hiredis
      - lapack
      - pybind
      - redis-plus-plus
      - cuda (optional)
      - cudnn (optional)
      - nccl (optional)
      - hip (optional)
      - hipcub (optional)
      - hipfft (optional)
      - hipsparse (optional)
      - miopen-hip (optional)
      - rccl (optional)
      - rocblas (optional)
      - rocfft (optional)
      - rocminfo (optional)
      - rocprim (optional)
      - rocrand (optional)
      - rocthrust (optional)
    - Python Packages:
      - absl-py
      - astor
      - asturneparse
      - async-timeout
      - cffi
      - colorama
      - flatbuffers
      - gast
      - google-pasta
      - grpcio
      - h5py
      - humanfriendly
      - importlib-metadata
      - jinja2
      - libclang
      - networkx
      - numpy
      - opt-einsum
      - pyyaml
      - requests
      - scipy
      - six
      - sympy
      - tensorboard
      - termcolor
      - typing_extensions
      - wrapt
- [x] CI facility: **all available** 

2. After this request is approved, you will be notified and asked to create a **Pull Request** with basic test recipes packed into `test.sh` inside the directory `ci/tests/<tool_name>`.

3. Once all the steps above have been completed, your tool will be activated in all the requested CI pipelines.

**Comment by mtitov** [comment]
@MattToast Thank you! This ticket is kept for records - associated PR #204
