### ISSUE TITLE
Initial test coverage for RadicalPilot

### ISSUE THREAD

**Issue by dongahn** [ExaWorks/SDK#31]
Following up one of my TODO items from 4/23 team meeting.

Tagging @andre-merzky . It will be nice if you can capture some of the key initial testing coverage for RadicalPilot in our SDK context here.

**Comment by andre-merzky** [comment]
test coverage for RP would consist of
  - unit tests: `pytest tests/unit_tests`
  - component tests: `pytest tests/component_tests`
  - end-to-end examples: `examples/00_getting_started.py` (and some others)
For testing on HPC resources we have additional integration tests - those do not make sense in a GitHub CI context, as they test the integration with batch systems and launchers.

@dongahn : is that the information this ticket is supposed to capture, or am I off target?

**Comment by dongahn** [comment]
Seems like a reasonable start from my perspective, @andre-merzky.

**Comment by dongahn** [comment]
@hategan, @j-woz, @SteVwonder: anything you want to add in terms of streamlining this effort to be reused for future pair-wise testing?

**Comment by andre-merzky** [comment]
This was resolved by merging #45
