### ISSUE TITLE
README.md DRAFT with rationale for our SDK approach

### ISSUE THREAD

**Issue by dongahn** [ExaWorks/SDK#37]
@j-woz agreed to create a draft PR on which all contributors can build.

**Comment by j-woz** [comment]
A render of this can be viewed here:
https://github.com/j-woz/SDK/blob/master/docker/swift-t/README.adoc

**Comment by dongahn** [comment]
@j-woz: thank you for PR #41 for Swift/T. Did you plan to draft the top-level `README.md` draft as well? Or do you want someone else to draft?

**Comment by j-woz** [comment]
I was thinking that if we can see a few more component-level READMEs, then we will be in better position to synthesize things into a top-level one.  Mine is really just for discussion to see if that is what people are looking for.

**Comment by dongahn** [comment]
This is done now.
