### ISSUE TITLE
CI: fix github container registry deploy

### ISSUE THREAD

**Issue by SteVwonder** [ExaWorks/SDK#49]
The CI deploy for docker hub is fixed with #44, but the github deploy is still broken with a permissions issue.

**Comment by SteVwonder** [comment]
I enabled packages at the organizational level, so I believe that will fix the issue.  I guess we will see after the next PR is merged.

**Comment by zekemorton** [comment]
Seems to be fixed, latest images have been pushed to docker hub successfully
