### ISSUE TITLE
Docker image for RadicalPilot

### ISSUE THREAD

**Issue by dongahn** [ExaWorks/SDK#5]
Creating a new subtask by breaking down from #2.
Docker image with the make-check running.

**Comment by dongahn** [comment]
@andre-merzky

**Comment by andre-merzky** [comment]
This will be a separate dockerfile for now - reopening

**Comment by dongahn** [comment]
@andre-merzky: now the base image has been merged, you can take a look.

**Comment by andre-merzky** [comment]
PR #20 provides that.

**Comment by dongahn** [comment]
Great!

**Comment by andre-merzky** [comment]
> Great! I see this has already been merged. Thanks.

Uhm, yes - we may want to discuss policies a bit I guess - sorry if that merge was premature!

**Comment by andre-merzky** [comment]
closed via #20
