### ISSUE TITLE
Need a Parsl Spack recipe

### ISSUE THREAD

**Issue by dongahn** [ExaWorks/SDK#58]

**Comment by dongahn** [comment]
Quick note from today's meeting:

@hategan had a discussion with @kylechard and other parsl folks.
- Contribution to Spack upstream is an easy part
- Fear is that recipe can quickly go out of sync without no active maintatence
- What’s left to do is a PR; 
TODO: @hategan to push for something more concrete by our next meeting.

@dongahn described how Flux does this. It upstreamed its recipe to Spack and put a Spack sync task in its release procedure: https://github.com/flux-framework/flux-core/wiki/Release-Checklist

**Comment by SteVwonder** [comment]
> Fear is that recipe can quickly go out of sync without no active maintatence
>  It (Flux) upstreamed its recipe to Spack and put a Spack sync task in its release procedure:

FWIW, in terms of releases, you can also add a function to your spack package that tells it how to fetch new versions that aren't explicitly listed in the package: https://spack.readthedocs.io/en/latest/packaging_guide.html#version-urls

So if you do happen to miss updating the Spack package for a particular version/release, a can user explicitly requests that version/release and it will still work.

**Comment by zekemorton** [comment]
I believe this complete, `spack install parsl` is successful
