### ISSUE TITLE
Documenting SDK

### ISSUE THREAD

**Issue by mturilli** [ExaWorks/SDK#62]
Review SDK and open issues with TODOs if any.

**Comment by dongahn** [comment]
Good discussion today. My main takeaway:

- We should build our documentation towards developer-focused who will use SDK to build their workflows. 
- As an intermediate step, he wants to gather internal documents each contributor have into a WIKI space. Later we will hoist up some of the key techniques from there to more user-focused, polished space (e.g., readthedoc). 
- In addition, a set of examples we will build for our SC21 tutorial should be documented such a way that this can go to the polished space later.

Once the Wiki category is created, this issue can be closed until we need further concrete actions.

**Comment by mturilli** [comment]
Closing this because we have more granular tickets about SDK documentation.
