### ISSUE TITLE
Build with MPICH

### ISSUE THREAD

**Issue by j-woz** [ExaWorks/SDK#64]
This can work in the SDK containers.  So far I have only tested with Swift/T.  What else do I need to test?  Do we have the CI infrastructure in place to switch on the ARG MPI ?

**Comment by SteVwonder** [comment]
> Do we have the CI infrastructure in place to switch on the ARG MPI ?

You can add a new [matrix variable]() for MPI variant in our [build strategy](https://github.com/ExaWorks/SDK/blob/master/.github/workflows/ci.yml#L13).

Also a heads up that #51 switches to a script-based approach for installing MPI in these commits:
- https://github.com/ExaWorks/SDK/pull/51/commits/16e394b393c79bf6875465616c07c258f7a05fa2
- https://github.com/ExaWorks/SDK/pull/51/commits/a54a103bb930b3bda8d1ccaa1b1c6ed9a9e6d912

I should have that PR squashed down and ready for re-review by COB today, so once that is merged, you can just update the `install-mpi.sh` script to look for an MPICH variant and install via (presumably) yum.

**Comment by j-woz** [comment]
Ok no problem.
