### ISSUE TITLE
CD: change the default CMD for the deployed SDK image

### ISSUE THREAD

**Issue by SteVwonder** [ExaWorks/SDK#66]
Currently, the `CMD` of the `exaworks/sdk` docker image is the test for the latest component to be built (currently `flux`).  This means if you run `docker run -ti exaworks/sdk:centos8`, you get:
```
Cloning into 'flux-core'...
remote: Enumerating objects: 84387, done.
remote: Counting objects: 100% (1389/1389), done.
remote: Compressing objects: 100% (637/637), done.
```

As the flux CI test begins to run.  As opposed to leaving the CMD as the smoketest for whichever component was added last, maybe we create an `sdk` directory that has a `Dockerfile` that just changes the `CMD` to something simple like `bash`.  That will result in a less surprising default behavior for anyone that runs the `exaworks/sdk` image.

**Comment by zekemorton** [comment]
This should be resolved when #121 is resolved. The changes already exist in the Integration docker file, we just need to add that to the deployment.
