### ISSUE TITLE
Docker image for Swift/T

### ISSUE THREAD

**Issue by dongahn** [ExaWorks/SDK#7]
Creating a new subtask by breaking down from #2.
Docker image with the make-check running.

**Comment by dongahn** [comment]
Tagging @jmjwozniak

**Comment by dongahn** [comment]
@jmjwozniak: now the base image has been merged, you can take a look.

**Comment by jmjwozniak** [comment]
So inside SDK/ , I should create a new /docker/swift-t/Dockerfile ?

**Comment by jmjwozniak** [comment]
That skeleton is almost complete, currently stuck on Tcl.

**Comment by jmjwozniak** [comment]
Ok I think this works now - is someone interested in testing?

**Comment by jmjwozniak** [comment]
Looking back at #2 it looks like I should have done OpenMPI first.  I will do that now.  How will we orchestrate testing both?

**Comment by dongahn** [comment]
@jmjwozniak: sorry for my late response. I was on  vacation (and off the grid :-) 

 > How will we orchestrate testing both?

I think testing orchestration needs to be done at the CI level, initially using GitHub Action. We probably don't need to run tests on applications that use both MPI implementations?

**Comment by dongahn** [comment]
FYI -- related to the need for multiple MPI coverage: https://github.com/flux-framework/flux-core/issues/3592#issuecomment-816346144

**Comment by jmjwozniak** [comment]
For multiple MPI, I meant separately testing OpenMPI and MPICH in totally different images/builds

**Comment by dongahn** [comment]
Yes, that makes a lot of sense.

**Comment by jmjwozniak** [comment]
- [ ] Merge multiple RUN lines into shell scripts
- [ ] Accept ARG for OpenMPI/MPICH
- [ ] Remove sanity checks
