### ISSUE TITLE
Add devel information to the documentation

### ISSUE THREAD

**Issue by mturilli** [ExaWorks/SDK#73]
Please use this link: https://github.com/ExaWorks/SDK/wiki

Information includes: scripts you used for developing and testing SDK, configuration options, design+architecture descriptions, etc.

**Comment by dongahn** [comment]
Great! Thank you @mturilli. 

Here, we specifically need to capture our findings on the CI infrastructure of LLNL, ORNL and ANL. Tagging @j-woz and @zekemorton.

**Comment by mturilli** [comment]
We may want to separate the documentation based on the categories of users we are going to serve. Categories:
- Workflow application developers: domain scientists that build on top of the core tools. Hide orchestration/resource management. Provide **recipes** on how to build a workflow application in a domain specific software layers (that we do not provide). YAML file that is fed to that layer than then uses SDK core tools.
- Facilities: how to deploy the tools aggregated under SDK, how to test them, how to configure them.

We may want to target only the facilities and leave to the documentation of each tool how to use those tools for workflow applications.
