### ISSUE TITLE
Manage python installation (for a specific python version)

### ISSUE THREAD

**Issue by mtitov** [ExaWorks/SDK#74]
Further functionality extension will let to control and manage python installation

With `pip` as a chosen package manager - python should be installed within the system - either from system's repo (default python package, e.g., for Ubuntu 20.04 it is python3.8) or built manually (check the proposed solution in PR [#72](https://github.com/ExaWorks/SDK/pull/72), which will be used for the next PR based on this ticket)

**Comment by zekemorton** [comment]
It looks like python 3.6 is now end of life, and Parsl now requires python>=3.7. We should prioritize this to solve that issue
