### ISSUE TITLE
Spack package for ExaWorks doesn't need mpix-launch-swift

### ISSUE THREAD

**Issue by eugeneswalker** [ExaWorks/SDK#78]
It sounds like the Spack package for `exaworks` does not need to depend on `mpix-launch-swift`, which is good because right now `mpix-launch-swift` is not building in Spack (https://github.com/spack/spack/issues/27163). Exaworks is not buildable via Spack until the build issue with `mpix-launch-swift` is resolved or it is removed as an explicit dependency from the `exaworks` package.

A PR was submitted to remove `mpix-launch-swift` from Spack here: https://github.com/spack/spack/pull/27192

But this won't solve the problem unless it also removes the explicit dependency statement from the `exaworks` package.py, as shown here: https://github.com/spack/spack/pull/27206

**Comment by mtitov** [comment]
`mpix-launch-swift` is removed from `exaworks` dependency, `stc` package is correct for that ([spack exaworks](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/exaworks/package.py))
