### ISSUE TITLE
Base: Add MPI ENV Variable 

### ISSUE THREAD

**Issue by zekemorton** [ExaWorks/SDK#79]
It would be useful to to know what mpi is installed, especially when running some tests. Primary example is the Swift-t tests, for openMPI, the variable `allow-run-as-root` is set, but this cause a run time error for mpich.

**Comment by andre-merzky** [comment]
We use a heuristic to determine MPI flavor - in case this might be useful, have a look [here](https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/agent/launch_method/base.py#L307)

**Comment by j-woz** [comment]
That looks fine- can we package that in base as a shell-accessible tool?
