### ISSUE TITLE
CI: Specify Ubunutu version for LLNL

### ISSUE THREAD

**Issue by zekemorton** [ExaWorks/SDK#80]
The CI Build matrix for LLNL currently only specifies `ubuntu` and not `ubuntu2004`. This does not pose an issue currently, but will if we plan to add an additional version of ubuntu. In order to build containers on LC machines, we need to use LC base images to ensure that we do not run into certificate errors. The current lc base image for ubuntu2004 is named `lc-ubuntu` and it is the only ubuntu image. 

In order to support an additional ubuntu version for container testing, we would need to add an additional lc ubuntu image for that version, and I propose that we address this issue then.

**Comment by zekemorton** [comment]
@mtitov I think you reviewed the PR and suggested this change. I verified that the LC ubuntu image is running 20.04, and have set the image to update with docker hub on a weekly basis to better match the GitHub tests. At this time, it doesn't not seem that we are planning to add additional ubuntu versions to the build matrix. Is there any reason we still need to make the changes or is this sufficient to close the issue?

**Comment by mtitov** [comment]
@zekemorton hi Zeke, yeah, I don't have any objections to keep it as it is now. We can close this ticket
