### ISSUE TITLE
Write documentation for container deployment

### ISSUE THREAD

**Issue by mturilli** [ExaWorks/SDK#88]
Branch `docs`

**Comment by kylechard** [comment]
Ideally we want both user and developer documentation.

**Comment by zekemorton** [comment]
Hey @mturilli,  I am just now getting to this. After looking at the documentation branch it looks like we are focusing in displaying our documentation via tutorials with Jupiter notebooks. I believe I can create a notebook with a bash kernel where I can go over usage of and development the sdk container. Is that what We were envisioning with this for the container deployment or something else entirely?

**Comment by mturilli** [comment]
Hey @zekemorton , thank you for looking into this. What we need to do is open to discussion but what you suggest seems useful to me.

**Comment by mturilli** [comment]
LGTM!
